pipeline{
    agent any
    stages{
        stage("init"){
            steps{
                sh "terraform init -no-color"
            }
            post{
                /*always{
                    echo "========always========"
                }*/
                success{
                    echo "Successfull initialization"
                }
                failure{
                    echo "fail initialization"
                }
            }
        }
        stage("validate"){
            steps{
                sh "terraform validate -no-color"
            }
            post{
                /*always{
                    echo "========always========"
                }*/
                success{
                    echo "Successfull validation"
                }
                failure{
                    echo "fail validation"
                }
            }
        }
        stage("format"){
            steps{
                sh "terraform fmt -no-color"
            }
            post{
                /*always{
                    echo "========always========"
                }*/
                success{
                    echo "Successfull format"
                }
                failure{
                    echo "fail format"
                }
            }
        }
        stage("plan"){
            steps{
                sh "terraform plan -var ${REGION}=${REGION} -var ${INSTANCE_TYPE}=${INSTANCE_TYPE} -var ${ENVIRONMENT}=${ENVIRONMENT} -no-color"
            }
            post{
                /*always{
                    echo "========always========"
                }*/
                success{
                    echo "Successfull plan"
                }
                failure{
                    echo "fail plan"
                }
            }
        }
    }
    /*post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }*/
}